projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/api.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 3
extensions:
  amplify:
    version: 3
