enum Paths {
  HOME = '/',
  ABOUT = '/about-us',
  CONTACT = '/contact',
  DONATE = '/donate',
  LOGIN = '/login',
  ADMIN_DASHBOARD = '/admin-dashboard',
  ADMIN_DASHBOARD_LA_MANAGE = '/admin-dashboard/la-manage',
  ADMIN_DASHBOARD_LA_VIEW = '/admin-dashboard/la-view',
  ADMIN_DASHBOARD_REQUESTS = '/admin-dashboard/requests',
  ADMIN_DASHBOARD_REQUESTS_SCHOOL = '/admin-dashboard/requests-school',
  ADMIN_DASHBOARD_REQUESTS_CHARITY = '/admin-dashboard/requests-charity',
  ADMIN_DASHBOARD_SIGN_UP = '/admin-dashboard/la-sign-up',
  ADMIN_DASHBOARD_SIGN_UP_CONFIRMATION = '/admin-dashboard/la-sign-up-confirmation',
  LOCAL_AUTHORITY_DASHBOARD = '/local-authority-dashboard',
  ACCESSABILITY_STATEMENT = '/accessibility-statement',
  YOUR_SCHOOL = '/school/your-school',
  SCHOOLS_DASHBOARD = '/school/schools-dashboard',
  PRIVACY_POLICY = '/privacy-policy',
  TERMS_AND_CONDITIONS = '/terms-and-conditions',
  WE_HAVE_THE_POWER = 'https://wehavethepower.org/',
  EQUALITY_SERVICES = 'https://www.equalityadvisoryservice.com/',
  EMAIL = 'mailto: team@donatetoeducate.org.uk',
  PTA = 'https://www.pta.co.uk/',
  FUNDED = 'https://www.funded.org.uk',
  INVENT = 'https://www.capgemini.com/about-us/who-we-are/our-brands/capgemini-invent/',
  RESET_PASSWORD = '/reset-password',
  SIGN_UP_CHARITY = '/sign-up-charity',
  SIGN_UP_SCHOOL = '/sign-up-school',
  ADD_USER = '/add-user',
  SCHOOL_EDIT = '/school-edit',
}

export default Paths;
