import { GetJoinRequestsQuery } from '@/types/api';
import { InstitutionType } from '@/types/data';

export const dataWithSchoolAndCharity: GetJoinRequestsQuery = {
  getJoinRequests: [
    {
      id: '75ccc782-c359-47cc-8a7e-43522ec9d4af',
      name: 'Test Test',
      localAuthority: 'West Sussex',
      type: InstitutionType.SCHOOL,
      requestTime: 1711394605001,
      status: 'NEW',
      email: 'Test@gmail.com',
      school: 'Test School',
      jobTitle: 'Test',
      phone: '07801234456',
      charityName: null,
      charityAddress: null,
      aboutCharity: null,
      urn: '123456',
      __typename: 'JoinRequest',
    },
    {
      id: '31c7091b-558e-4087-8a54-2f176f76e894',
      name: 'Test Test',
      localAuthority: 'Hammersmith and Fulham',
      type: InstitutionType.CHARITY,
      requestTime: 1711394803223,
      status: 'NEW',
      email: 'Test@gmail.com',
      school: '',
      jobTitle: 'Test',
      phone: '07803123755',
      charityName: 'Test',
      charityAddress:
        'Test\n          \n          Test\n          Test\n          Testttt\n          ',
      aboutCharity: 'Test',
      urn: null,
      __typename: 'JoinRequest',
    },
  ],
};

export const dataWithMultipleSchools: GetJoinRequestsQuery = {
  getJoinRequests: [
    {
      id: '75ccc782-c359-47cc-8a7e-43522ec9d4af',
      name: 'Test Test',
      localAuthority: 'West Sussex',
      type: InstitutionType.SCHOOL,
      requestTime: 1711394605001,
      status: 'NEW',
      email: 'Test@gmail.com',
      school: 'Test School',
      jobTitle: 'Test',
      phone: '07801234456',
      charityName: null,
      charityAddress: null,
      aboutCharity: null,
      urn: '123456',
      __typename: 'JoinRequest',
    },
    {
      id: '31c7091b-558e-4087-8a54-2f176f76e894',
      name: 'Test Test two',
      localAuthority: 'Hammersmith and Fulham',
      type: InstitutionType.SCHOOL,
      requestTime: 1711394605100,
      status: 'NEW',
      email: 'Test@gmail.com',
      school: 'Test School Two',
      jobTitle: 'Test',
      phone: '07803123755',
      charityName: null,
      charityAddress: null,
      aboutCharity: null,
      urn: null,
      __typename: 'JoinRequest',
    },
  ],
};
