import { ItemsIconType, getItemsIcon, getSectionsIcon } from './getIcons';

interface ItemList {
  icon: JSX.Element;
  name: string;
  items: string[];
  itemIcon: JSX.Element;
}
[];

export const getFullItemList = (type: ItemsIconType): ItemList[] => {
  return [
    {
      icon: getSectionsIcon('shirt'),
      name: 'Clothing and uniform',
      items: [
        'Coats',
        'Shoes',
        'Hats',
        'Wellies',
        'Trousers',
        'Shirts',
        'Dresses',
        'Skirts',
        'Polo shirts',
        'Socks',
        'Shorts',
        'Cardigans',
        'Blazers',
        'Jumpers',
        'Ties',
        'Tights',
        'Summer dresses',
        'Name labels',
        'Gloves',
        'Scarves',
        'Pinafores',
        'Summer pinafores',
      ].sort(),
      itemIcon: getItemsIcon(type),
    },
    {
      icon: getSectionsIcon('ball'),
      name: 'Sports',
      items: [
        'Football boots',
        'Trainers',
        'Gym shoes',
        'T-shirts',
        'Shorts',
        'Jumpers',
        'Hoodies',
        'Plimsolls',
        'Socks',
        'Gym bag',
        'Skirts',
        'Gym vest',
        'Hockey sticks',
        'Footballs',
        'Netballs',
        'Hockey balls',
        'Skorts',
        'Mouth guards',
        'Shin pads',
        'Water bottle',
      ].sort(),
      itemIcon: getItemsIcon(type),
    },
    {
      icon: getSectionsIcon('brush'),
      name: 'Art and music',
      items: [
        'Sketch books',
        'Pencils',
        'Paints',
        'Crayons',
        'Felt tips',
        'Rubbers',
        'Glue stick',
        'Recorders',
        'Violins',
        'Flutes',
        'Triangles',
        'Keyboards',
        'Guitars',
        'Music score books',
      ].sort(),
      itemIcon: getItemsIcon(type),
    },
    {
      icon: getSectionsIcon('book'),
      name: 'Study',
      items: [
        'Book bags',
        'Backpacks',
        'Lunchboxes',
        'Textbooks',
        'Revision guides',
        'Books',
        'Dictionary',
        'Thesaurus',
        'Anthologies',
        'Online tuition',
        'Past exam papers',
        'Pencil cases',
        'Highlighters',
        'Rulers',
        'Pencils',
        'Sharpeners',
        'Calculators',
        'Protractor',
        'Geometry sets',
        'Handwriting pens',
        'Rubbers',
        'Glue stick',
        'Lined notebook',
        'Compass',
      ].sort(),
      itemIcon: getItemsIcon(type),
    },
    {
      icon: getSectionsIcon('sink'),
      name: 'Toiletries',
      items: [
        'Shower gel',
        'Handwash',
        'Sanitary pads',
        'Tampons',
        'Toothbrushes',
        'Toothpaste',
        'Shampoo',
        'Conditioner',
        'Reusable sanitary products',
      ].sort(),
      itemIcon: getItemsIcon(type),
    },
    {
      icon: getSectionsIcon('computer'),
      name: 'Computing and technology',
      items: ['Laptops', 'Tablets', 'Computer software', 'Internet access'].sort(),
      itemIcon: getItemsIcon(type),
    },
  ];
};
